Repository shotly/shotly, pull requests merged in 2025-07, with the labels that each got.

#4 chore(deps): update pnpm.catalog.default nuxt to ^3.17.6
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#10 feat(web): update confirmation modal and error handling
  apps/web/app/components/ButtonDelete.vue
  apps/web/app/components/ModalConfirm.vue
  apps/web/app/components/UserDropdown.vue
  apps/web/app/components/profile/ProfileFormDangerZone.vue
  apps/web/app/composables/useLogout.ts
  apps/web/app/layouts/with-aside.vue
  apps/web/app/plugins/1.api.ts
  apps/web/i18n/locales/en-US.json
  apps/web/i18n/locales/ru-RU.json
Labels: 0.x

#7 chore(deps): update all non-major dependencies
  apps/landing/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#49 docs: add roadmap page with volta
  apps/landing/app/pages/roadmap.vue
Labels: documentation

#62 feat: implement crud webhooks
  apps/web/app/components/webhooks/WebhooksFormCreate.vue
  apps/web/app/components/webhooks/WebhooksList.vue
  apps/web/app/components/webhooks/WebhooksViewModal.vue
  apps/web/app/pages/settings/webhooks.vue
  apps/web/i18n/locales/en-US.json
  apps/web/i18n/locales/ru-RU.json
  apps/web/server/api/api-keys/index.post.ts
  apps/web/server/api/webhooks/[id].delete.ts
  apps/web/server/api/webhooks/index.get.ts
  apps/web/server/api/webhooks/index.post.ts
  apps/web/shared/api/enums.ts
  apps/web/shared/api/index.ts
  apps/web/shared/api/types.ts
  apps/web/shared/api/zod.ts
  packages/db/migrations/0004_naive_punisher.sql
  packages/db/migrations/meta/0004_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/tables.ts
  specs/web.yml
Labels: enhancement, 0.x

#71 feat: add appearance page
  apps/web/app/components/appearance/AppearanceFormLocale.vue
  apps/web/app/components/appearance/AppearanceFormTheme.vue
  apps/web/app/components/aside/AsideSettings.vue
  apps/web/app/components/webhooks/WebhooksFormCreate.vue
  apps/web/app/layouts/default.vue
  apps/web/app/pages/settings/appearance.vue
  apps/web/app/pages/settings/profile.vue
  apps/web/i18n/locales/en-US.json
  apps/web/i18n/locales/ru-RU.json
  packages/base/app/components/PageCard.vue
  packages/base/app/components/PageHeader.vue
Labels: enhancement, 0.x

#75 fix: github counter stars
  apps/landing/server/utils/github.ts
Labels: bug

#67 chore(deps): update all non-major dependencies
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#88 refactor: overall design
  apps/web/app/components/apiKeys/ApiKeysFormCreate.vue
  apps/web/app/components/apiKeys/ApiKeysViewModal.vue
  apps/web/app/components/aside/AsideBookmarks.vue
  apps/web/app/components/collections/CollectionsFormModal.vue
  apps/web/app/components/collections/CollectionsMenu.vue
  apps/web/app/components/collections/CollectionsShareModal.vue
  apps/web/app/components/profile/ProfileFormDetails.vue
  apps/web/app/components/webhooks/WebhooksFormCreate.vue
  apps/web/app/components/webhooks/WebhooksViewModal.vue
  apps/web/app/layouts/default.vue
  apps/web/app/layouts/with-aside.vue
  apps/web/i18n/locales/en-US.json
  apps/web/i18n/locales/ru-RU.json
  packages/base/app/app.config.ts
  packages/base/app/components/ModalBrand.vue
  packages/base/app/components/ModalConfirm.vue
  packages/base/i18n/locales/en-US.json
  packages/base/i18n/locales/ru-RU.json
Labels: enhancement, 0.x

#89 chore(deps): update all non-major dependencies
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies

#92 refactor: remove normalization collections
  apps/web/server/api/collections/index.get.ts
Labels: enhancement, 0.x

#93 feat: add collections description field
  apps/web/app/components/collections/CollectionsFormModal.vue
  apps/web/app/components/collections/CollectionsMenuView.vue
  apps/web/i18n/locales/en-US.json
  apps/web/i18n/locales/ru-RU.json
  apps/web/server/api/collections/[id]/index.put.ts
  apps/web/server/api/collections/index.post.ts
  apps/web/shared/api/types.ts
  apps/web/shared/api/zod.ts
  packages/base/app/components/InputClearable.vue
  packages/base/app/components/SelectMenuClearable.vue
  specs/web.yml
Labels: enhancement, 0.x

#96 chore(deps): update node.js to v22.17.1
  docker/web/Dockerfile
Labels: dependencies

#105 chore(deps): update all non-major dependencies
  apps/web/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#106 chore(deps): update pnpm.catalog.default nuxt to ^4.0.1
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#107 chore(deps): update all non-major dependencies
  apps/landing/package.json
  apps/web/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: dependencies

#113 chore(deps): update all non-major dependencies
  apps/landing/package.json
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies
